name: at_data_browser
description: A new Flutter project
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  at_app_flutter: ^5.0.1
  at_client_mobile: ^3.2.6
  at_onboarding_flutter: ^5.0.3
  at_utils: ^3.0.11
  biometric_storage: ^4.1.3
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  hive: ^2.2.3
  path_provider: ^2.0.11

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - .env
