name: at_data_browser
description: A new Flutter project
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  at_app_flutter: ^5.0.1
  at_client_mobile: ^3.2.6
  at_common_flutter: ^2.0.11
  at_contact: 3.0.6
  at_contacts_flutter: ^4.0.9
  at_onboarding_flutter: ^6.0.3
  at_utils: ^3.0.11
  biometric_storage: ^4.1.3
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.3.4
  hive: ^2.2.3
  intl: any
  package_info_plus_windows: ^2.1.0
  path_provider: ^2.0.11
  recase: ^4.1.0
  shared_preferences: ^2.1.0
  url_launcher: ^6.1.11

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

dependency_overrides:
  at_contact: 3.0.6
  intl: 0.18.1

flutter:
  generate: true
  uses-material-design: true
  assets:
    - .env
